-- =====================================================
-- BARCLAYS HANDS-ON LAB
-- STEP 3 VALIDATION: Verify dbt output matches spec
-- Run this AFTER Cortex Code completes dbt run + dbt test
-- =====================================================

USE WAREHOUSE BARCLAYS_WH;
USE DATABASE BARCLAYS_HOL;

-- 1. Check all 3 tables exist in ANALYTICS
WITH expected_tables AS (
    SELECT column1 AS TABLE_NAME FROM VALUES
        ('STG_PAYMENTS'),
        ('MART_PAYMENT_KPIS'),
        ('MART_SLA_COMPLIANCE')
),
actual_tables AS (
    SELECT TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'ANALYTICS' AND TABLE_TYPE = 'BASE TABLE'
)
SELECT
    e.TABLE_NAME,
    IFF(a.TABLE_NAME IS NOT NULL, 'PASS', 'FAIL - TABLE MISSING') AS STATUS
FROM expected_tables e
LEFT JOIN actual_tables a ON e.TABLE_NAME = a.TABLE_NAME;

-- 2. Check all expected columns exist per table
WITH expected_columns AS (
    SELECT column1 AS TABLE_NAME, column2 AS COLUMN_NAME FROM VALUES
        -- stg_payments
        ('STG_PAYMENTS', 'PAYMENT_ID'),
        ('STG_PAYMENTS', 'PAYMENT_DATE'),
        ('STG_PAYMENTS', 'PAYMENT_TYPE'),
        ('STG_PAYMENTS', 'CHANNEL'),
        ('STG_PAYMENTS', 'CURRENCY'),
        ('STG_PAYMENTS', 'AMOUNT'),
        ('STG_PAYMENTS', 'STATUS'),
        ('STG_PAYMENTS', 'PROCESSING_TIME_MS'),
        ('STG_PAYMENTS', 'REGION'),
        ('STG_PAYMENTS', 'IS_SUCCESSFUL'),
        ('STG_PAYMENTS', 'IS_FAILED'),
        -- mart_payment_kpis
        ('MART_PAYMENT_KPIS', 'PAYMENT_DATE'),
        ('MART_PAYMENT_KPIS', 'PAYMENT_TYPE'),
        ('MART_PAYMENT_KPIS', 'REGION'),
        ('MART_PAYMENT_KPIS', 'TOTAL_PAYMENTS'),
        ('MART_PAYMENT_KPIS', 'TOTAL_VOLUME'),
        ('MART_PAYMENT_KPIS', 'SUCCESS_RATE_PCT'),
        ('MART_PAYMENT_KPIS', 'AVG_PROCESSING_TIME_MS'),
        ('MART_PAYMENT_KPIS', 'P95_PROCESSING_TIME_MS'),
        -- mart_sla_compliance
        ('MART_SLA_COMPLIANCE', 'PAYMENT_DATE'),
        ('MART_SLA_COMPLIANCE', 'PAYMENT_TYPE'),
        ('MART_SLA_COMPLIANCE', 'REGION'),
        ('MART_SLA_COMPLIANCE', 'SLA_TARGET_SUCCESS_RATE'),
        ('MART_SLA_COMPLIANCE', 'SUCCESS_RATE_PCT'),
        ('MART_SLA_COMPLIANCE', 'P95_PROCESSING_TIME_MS'),
        ('MART_SLA_COMPLIANCE', 'MAX_PROCESSING_TIME_MS'),
        ('MART_SLA_COMPLIANCE', 'SLA_STATUS')
),
actual_columns AS (
    SELECT TABLE_NAME, COLUMN_NAME
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'ANALYTICS'
)
SELECT
    e.TABLE_NAME,
    e.COLUMN_NAME,
    IFF(a.COLUMN_NAME IS NOT NULL, 'PASS', 'FAIL - COLUMN MISSING') AS STATUS
FROM expected_columns e
LEFT JOIN actual_columns a ON e.TABLE_NAME = a.TABLE_NAME AND e.COLUMN_NAME = a.COLUMN_NAME
ORDER BY e.TABLE_NAME, e.COLUMN_NAME;

-- 3. Check data integrity (rows exist and values are sensible)
SELECT
    'STG_PAYMENTS' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    IFF(COUNT(*) >= 50000, 'PASS', 'FAIL - ROW COUNT LOW') AS STATUS
FROM ANALYTICS.STG_PAYMENTS
UNION ALL
SELECT
    'MART_PAYMENT_KPIS',
    COUNT(*),
    IFF(COUNT(*) > 100, 'PASS', 'FAIL - ROW COUNT LOW')
FROM ANALYTICS.MART_PAYMENT_KPIS
UNION ALL
SELECT
    'MART_SLA_COMPLIANCE',
    COUNT(*),
    IFF(COUNT(*) > 10, 'PASS', 'FAIL - ROW COUNT LOW')
FROM ANALYTICS.MART_SLA_COMPLIANCE;

-- 4. Check SLA_STATUS contains only expected values
SELECT
    SLA_STATUS,
    COUNT(*) AS COUNT,
    IFF(SLA_STATUS IN ('COMPLIANT', 'AT RISK', 'BREACH'), 'PASS', 'FAIL - UNEXPECTED VALUE') AS STATUS
FROM ANALYTICS.MART_SLA_COMPLIANCE
GROUP BY SLA_STATUS;

-- 5. Final verdict
SELECT
    IFF(
        (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='ANALYTICS' AND TABLE_NAME IN ('STG_PAYMENTS','MART_PAYMENT_KPIS','MART_SLA_COMPLIANCE')) = 3
        AND (SELECT COUNT(*) FROM ANALYTICS.MART_SLA_COMPLIANCE WHERE SLA_STATUS IN ('COMPLIANT','AT RISK','BREACH')) > 0
        AND (SELECT COUNT(*) FROM ANALYTICS.MART_PAYMENT_KPIS WHERE SUCCESS_RATE_PCT BETWEEN 0 AND 100) > 0,
        '✅ ALL CHECKS PASSED - proceed to Step 4',
        '❌ VALIDATION FAILED - ask Cortex Code to fix the issues shown above'
    ) AS FINAL_VERDICT;
