-- =====================================================
-- BARCLAYS HANDS-ON LAB
-- STEP 4: CORTEX AI ENRICHMENT
-- Run AFTER dbt models have been deployed (Step 3)
-- =====================================================

USE WAREHOUSE BARCLAYS_WH;
USE SCHEMA BARCLAYS_HOL.ANALYTICS;

-- 4.1: Sentiment analysis on customer feedback
CREATE OR REPLACE TABLE FEEDBACK_ENRICHED AS
SELECT
    f.FEEDBACK_ID,
    f.FEEDBACK_DATE,
    f.CUSTOMER_NAME,
    f.FEEDBACK_CHANNEL,
    f.FEEDBACK_TEXT,
    f.PAYMENT_TYPE,
    f.RATING,

    -- Sentiment score: -1.0 (very negative) to +1.0 (very positive)
    ROUND(SNOWFLAKE.CORTEX.SENTIMENT(f.FEEDBACK_TEXT), 3) AS SENTIMENT_SCORE,

    CASE
        WHEN SNOWFLAKE.CORTEX.SENTIMENT(f.FEEDBACK_TEXT) >  0.3 THEN 'POSITIVE'
        WHEN SNOWFLAKE.CORTEX.SENTIMENT(f.FEEDBACK_TEXT) < -0.3 THEN 'NEGATIVE'
        ELSE 'NEUTRAL'
    END AS SENTIMENT_LABEL,

    -- Auto-classify topic from the feedback text
    SNOWFLAKE.CORTEX.CLASSIFY_TEXT(
        f.FEEDBACK_TEXT,
        ['Performance Issue','Service Quality','Technical Problem','Positive Experience','Feature Request']
    ):label::STRING AS TOPIC_CATEGORY,

    SNOWFLAKE.CORTEX.CLASSIFY_TEXT(
        f.FEEDBACK_TEXT,
        ['Performance Issue','Service Quality','Technical Problem','Positive Experience','Feature Request']
    ):score::FLOAT AS CLASSIFICATION_CONFIDENCE

FROM BARCLAYS_HOL.RAW_DATA.CUSTOMER_FEEDBACK f;

-- Preview
SELECT
    FEEDBACK_TEXT,
    SENTIMENT_SCORE,
    SENTIMENT_LABEL,
    TOPIC_CATEGORY,
    ROUND(CLASSIFICATION_CONFIDENCE, 2) AS CONFIDENCE
FROM FEEDBACK_ENRICHED
LIMIT 10;

-- 4.2: AI-generated recommended actions for open high-severity alerts
SELECT
    a.ALERT_ID,
    a.SEVERITY,
    a.ALERT_DESCRIPTION,
    a.PAYMENT_TYPE,
    SNOWFLAKE.CORTEX.COMPLETE(
        'mistral-large2',
        'You are a payments operations analyst at a major UK bank. ' ||
        'Given this alert: "' || a.ALERT_DESCRIPTION || '" ' ||
        'for payment type: ' || a.PAYMENT_TYPE || ' ' ||
        'with severity: ' || a.SEVERITY || '. ' ||
        'Provide a one-sentence recommended action.'
    ) AS AI_RECOMMENDED_ACTION
FROM BARCLAYS_HOL.RAW_DATA.OPERATIONAL_ALERTS a
WHERE a.STATUS = 'OPEN'
  AND a.SEVERITY IN ('HIGH','CRITICAL')
LIMIT 5;

-- 4.3: Sentiment distribution
SELECT
    SENTIMENT_LABEL,
    COUNT(*) AS FEEDBACK_COUNT,
    ROUND(AVG(SENTIMENT_SCORE), 3) AS AVG_SCORE,
    ROUND(COUNT(*)::FLOAT / (SELECT COUNT(*) FROM FEEDBACK_ENRICHED) * 100, 1) AS PERCENTAGE
FROM FEEDBACK_ENRICHED
GROUP BY SENTIMENT_LABEL
ORDER BY FEEDBACK_COUNT DESC;

-- 4.4: Sentiment by payment type
SELECT
    PAYMENT_TYPE,
    COUNT(*) AS TOTAL_FEEDBACK,
    ROUND(AVG(SENTIMENT_SCORE), 3) AS AVG_SENTIMENT,
    COUNT(CASE WHEN SENTIMENT_LABEL = 'NEGATIVE' THEN 1 END) AS NEGATIVE_COUNT,
    ROUND(COUNT(CASE WHEN SENTIMENT_LABEL = 'NEGATIVE' THEN 1 END)::FLOAT / COUNT(*) * 100, 1) AS NEGATIVE_PCT
FROM FEEDBACK_ENRICHED
GROUP BY PAYMENT_TYPE
ORDER BY AVG_SENTIMENT ASC;

-- =====================================================
-- 4.5: DYNAMIC TABLES - Real-Time Operational Layer
-- These refresh automatically when source data changes
-- =====================================================

-- DT 1: Live Negative Sentiment Alert Feed
-- Surfaces negative feedback within the last 24 hours, refreshing every minute
CREATE OR REPLACE DYNAMIC TABLE DT_NEGATIVE_SENTIMENT_FEED
    TARGET_LAG = '1 minute'
    WAREHOUSE = BARCLAYS_WH
AS
SELECT
    FEEDBACK_ID,
    FEEDBACK_DATE,
    CUSTOMER_NAME,
    PAYMENT_TYPE,
    FEEDBACK_CHANNEL,
    FEEDBACK_TEXT,
    SENTIMENT_SCORE,
    TOPIC_CATEGORY,
    CLASSIFICATION_CONFIDENCE
FROM FEEDBACK_ENRICHED
WHERE SENTIMENT_LABEL = 'NEGATIVE'
  AND FEEDBACK_DATE >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
ORDER BY FEEDBACK_DATE DESC;

-- Preview the live feed
SELECT * FROM DT_NEGATIVE_SENTIMENT_FEED LIMIT 10;

-- DT 2: Operational Sentiment Summary (cascading - refreshes downstream)
CREATE OR REPLACE DYNAMIC TABLE DT_SENTIMENT_OPS_SUMMARY
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = BARCLAYS_WH
AS
SELECT
    PAYMENT_TYPE,
    COUNT(*) AS TOTAL_FEEDBACK,
    COUNT(CASE WHEN SENTIMENT_LABEL = 'NEGATIVE' THEN 1 END) AS NEGATIVE_COUNT,
    COUNT(CASE WHEN SENTIMENT_LABEL = 'POSITIVE' THEN 1 END) AS POSITIVE_COUNT,
    ROUND(AVG(SENTIMENT_SCORE), 3) AS AVG_SENTIMENT,
    ROUND(COUNT(CASE WHEN SENTIMENT_LABEL = 'NEGATIVE' THEN 1 END)::FLOAT / COUNT(*) * 100, 1) AS NEGATIVE_PCT,
    MAX(FEEDBACK_DATE) AS LATEST_FEEDBACK
FROM FEEDBACK_ENRICHED
GROUP BY PAYMENT_TYPE;

-- View the operational summary
SELECT * FROM DT_SENTIMENT_OPS_SUMMARY ORDER BY NEGATIVE_PCT DESC;

-- DT 3: Live SLA Breach Counter
-- Counts active SLA breaches from the dbt mart, refreshing every minute
CREATE OR REPLACE DYNAMIC TABLE DT_LIVE_BREACH_COUNT
    TARGET_LAG = '1 minute'
    WAREHOUSE = BARCLAYS_WH
AS
SELECT
    PAYMENT_TYPE,
    COUNT(*) AS BREACH_DAYS,
    MIN(PAYMENT_DATE) AS FIRST_BREACH,
    MAX(PAYMENT_DATE) AS LATEST_BREACH
FROM MART_SLA_COMPLIANCE
WHERE SLA_STATUS = 'BREACH'
  AND PAYMENT_DATE >= DATEADD('day', -7, CURRENT_DATE())
GROUP BY PAYMENT_TYPE;

-- View active breaches
SELECT * FROM DT_LIVE_BREACH_COUNT ORDER BY BREACH_DAYS DESC;

-- Monitor Dynamic Table health
SHOW DYNAMIC TABLES IN SCHEMA ANALYTICS;

-- Check refresh history
SELECT
    NAME,
    STATE,
    REFRESH_START_TIME,
    REFRESH_END_TIME,
    TIMEDIFF('second', REFRESH_START_TIME, REFRESH_END_TIME) AS DURATION_SECONDS
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
    NAME => 'ANALYTICS.DT_NEGATIVE_SENTIMENT_FEED'
))
ORDER BY REFRESH_START_TIME DESC
LIMIT 5;
