-- =====================================================
-- BARCLAYS HANDS-ON LAB
-- STEP 6: DOCUMENT & DESCRIBE
-- Add metadata so objects are discoverable in the
-- Snowflake Data Catalog / Snowsight
-- =====================================================

USE WAREHOUSE BARCLAYS_WH;
USE DATABASE BARCLAYS_HOL;

-- 6.1: Document raw tables
COMMENT ON TABLE RAW_DATA.PAYMENTS IS
    'Raw inbound payment transactions. Source: payments processing system. Refreshed daily. Owner: Payments Operations.';

COMMENT ON TABLE RAW_DATA.CUSTOMER_FEEDBACK IS
    'Customer feedback on payment services collected across all channels. Owner: Customer Experience.';

COMMENT ON TABLE RAW_DATA.SLA_DEFINITIONS IS
    'Service Level Agreement thresholds for each payment type. Owner: Payments Operations.';

COMMENT ON TABLE RAW_DATA.OPERATIONAL_ALERTS IS
    'Operational alerts generated by the payments monitoring system. Owner: Payments Operations.';

-- 6.2: Document key columns on PAYMENTS
COMMENT ON COLUMN RAW_DATA.PAYMENTS.PAYMENT_ID         IS 'Unique identifier for each payment transaction.';
COMMENT ON COLUMN RAW_DATA.PAYMENTS.PAYMENT_TYPE       IS 'Payment scheme: SWIFT, BACS, CHAPS, Faster Payments, SEPA, Wire Transfer.';
COMMENT ON COLUMN RAW_DATA.PAYMENTS.STATUS             IS 'Current payment status: COMPLETED, PENDING, FAILED, RETURNED.';
COMMENT ON COLUMN RAW_DATA.PAYMENTS.PROCESSING_TIME_MS IS 'End-to-end processing time in milliseconds. Used for SLA compliance measurement.';
COMMENT ON COLUMN RAW_DATA.PAYMENTS.AMOUNT             IS 'Payment amount in the transaction currency.';

-- 6.3: Document dbt mart tables
COMMENT ON TABLE ANALYTICS.MART_PAYMENT_KPIS IS
    'dbt mart: daily payment KPIs aggregated by payment type and region. Includes success rates and processing time percentiles.';

COMMENT ON TABLE ANALYTICS.MART_SLA_COMPLIANCE IS
    'dbt mart: daily SLA compliance status per payment type. Joins KPIs against SLA_DEFINITIONS thresholds.';

-- 6.4: Document AI-enriched table
COMMENT ON TABLE ANALYTICS.FEEDBACK_ENRICHED IS
    'Cortex AI-enriched customer feedback. Includes sentiment scores (SNOWFLAKE.CORTEX.SENTIMENT) and topic classification (SNOWFLAKE.CORTEX.CLASSIFY_TEXT).';

-- 6.5: Document analytics view
COMMENT ON VIEW ANALYTICS.V_PAYMENTS_ANALYSIS IS
    'Unified analytics view for Snowflake CoWork. Exposes payment KPIs with time, type, and region dimensions. Used by SV_PAYMENTS_BARCLAYS Semantic View.';

-- 6.6: Verify all comments are visible
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('RAW_DATA','ANALYTICS')
  AND COMMENT IS NOT NULL
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- 6.7: Column comments
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    COMMENT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'RAW_DATA'
  AND TABLE_NAME   = 'PAYMENTS'
  AND COMMENT IS NOT NULL
ORDER BY ORDINAL_POSITION;

SELECT '✅ Documentation complete — objects now discoverable in Snowsight Data Catalog' AS STATUS;
